### PR TITLE
Handling Events was translated

### PR DESCRIPTION
**Pull request by saidfagan**

### CODE REVIEW

**Comment by saidfagan** [comment]
Why are yo so passive guys? In this way we will never finish the translation

**Comment by GasimGasimzada** [comment]
@saidfagan We have been quite busy last week and didn't get the time to check this one out. In the meantime, you can try to take another task and start working on them.

**Comment by azizaismayilova** [comment]
Hi @saidfagan, sorry for reviewing the translation late. It was a busy week. Here are my corrections:
- Line 14 -... hadisə **işlədicisi** kimi
- Line 16 - no need for comma
- Line 59 - DOM **elementi** yarandıqda
- Line 141 - ondan ** ibarətdir ki, **

**Comment by azizaismayilova** [comment]
Btw, the title needs to be discussed @GasimGasimzada @saidfagan

**Comment by saidfagan** [comment]
Made fixes. We've already discussed title. But if you have any suggestions, please make.

**Comment by GasimGasimzada** [comment]
Merged with minor changes.

**Pull request merged**
