### PR TITLE
State and lifecycles

### PR DESCRIPTION
**Pull request by saidfagan**

### CODE REVIEW

**Comment by GasimGasimzada** [comment]
Hello @saidfagan,

Could you please translate the title of the page? It is currently in Azerbaijani. Additionally, we try to localize the contents of the source code to make. Otherwise, I think it is fine. @azizaismayilova Could you please check for grammar in case I missed something?

Thanks!

**Comment by azizaismayilova** [comment]
Hi @saidfagan @GasimGasimzada  here is the list of corrections:

- [ ] Line 34 - ... etməyi **öyrənəcəyik**.
- [ ] Line 60 - ... önəmli **çatışmazlığı**
- [ ] Line 106 - **Öncəliklə**  funksiya...
- [ ] Line 168 - ... əlavə **edəcəyik.**
- [ ] Line 197 - ... **komponentində**...
- [ ] Line 205 - ... taymeri **yaddaşdan** silmək
- [ ] Line 207 -  ... ** metodları** ...
- [ ] Line 248 -  ... **ID-sini**
- [ ] Line 250 -  rewrite sentence
- [ ] Line 252 -  ... **siləcəyik.**
- [ ] Line 259 -  correct the verb
- [ ] Line 311 - Sentences in Azerbaijani can not start with "və"
- [ ] Line 317 - delete "və and merge sentences.
- [ ] Line 356 -First sencense  ... ikinci **formanı** . Second sentence "... arqument kimi isə **propların** "
- [ ] Line 365 -  ...  arrow **funksiyasını** istifadə...
- [ ] Line 378 - ... obyekti **hazırki** state-ə 
- [ ] Line 414 - Sentences in Azerbaijani can not start with "və"
- [ ] Line 430 - Please translate "props" to "proplar"

**Comment by GasimGasimzada** [comment]
@saidfagan any info on these changes?

**Comment by saidfagan** [comment]
Hi guys. Sorry for the delay, been busy last few days. I will make and push all of these corrections today or tomorrow.

**Comment by GasimGasimzada** [comment]
No problem. Thank you for the notice:)

**Comment by saidfagan** [comment]
Made required changes. Please merge.

**Comment by azizaismayilova** [comment]
Hi @saidfagan , there are a few mistakes that I found.

In line 207, don't make is bold. İ accidentally made a typing mistake in the comment.
Line 259, change the verb to "yaradacağıq".

**Comment by GasimGasimzada** [comment]
Merged! :)

**Comment by saidfagan** [comment]
Thanks.

**Comment by saidfagan** [comment]
And special thanks to @azizaismayilova for indicating mistakes. I will try to improve my skills in the future and make less mistakes.

**Pull request merged**
