### PR TITLE
Change "Dərsiliyi Götür" to "Dərsliyə Başla"

### PR DESCRIPTION
**Pull request by Haqverdi**
Change Dərsiliyi Götür to Dərsliyə Başla

### CODE REVIEW

**Comment by GasimGasimzada** [comment]
I disagree with this merely from "marketing" perspective. If you currently go to the preview, the button and the text do no clash in terms of words: https://deploy-preview-24--az-reactjs.netlify.com

However, if we change it to "başla," the two buttons will clash. Maybe "dərsliyi oxu?"

**Comment by Haqverdi** [comment]
> I disagree with this merely from "marketing" perspective. If you currently go to the preview, the button and the text do no clash in terms of words: https://deploy-preview-24--az-reactjs.netlify.com
> 
> However, if we change it to "başla," the two buttons will clash. Maybe "dərsliyi oxu"?

yes it is also possible as "dərsliyi oxu", but not "Dərsliyi Götür"

**Comment by GasimGasimzada** [comment]
Then I say lets do Dersliyi Oxu because then we will have Bashlamag and Dersliyi Oxu instead of Bashlamag and Dersliyi Bashla. If you agree, please make the changes and push.

**Comment by Haqverdi** [comment]
updated to "Dərsliyi Oxu"

**Comment by GasimGasimzada** [comment]
Wasn’t there two places for that button? One at the top and another one at the bottom?

**Pull request merged**
