### PR TITLE
Translate Code Splitting

### PR DESCRIPTION
**Pull request by GasimGasimzada**
- [x] Bundling
- [x] Code Splitting
- [x] Route based splitting
- [x] Named Exports

### CODE REVIEW

**Comment by tesseralis** [comment]
@Haqverdi are you ready to merge this in? It doesn't seem like there are a lot of you so it might not be a good idea to have two reviewers per page.

**Comment by Haqverdi** [comment]
> @Haqverdi are you ready to merge this in? It doesn't seem like there are a lot of you so it might not be a good idea to have two reviewers per page.

Yes, I checked the main parts, everything seems to be okay, unfortunately we are 2-3 people for now,  therefore have to do so in order to translate as soon as possible.

**Comment by azizaismayilova** [comment]
@tesseralis I have checked the content and there are some issues (typos, grammar issues). I will push them, once they are all fixed.

**Comment by Haqverdi** [comment]
I think we should translate the main part as soon as possible, then correct the shortcomings

**Pull request merged**
