### PR TITLE
Translated languages' page and list

### PR DESCRIPTION
**Pull request by saidfagan**

### CODE REVIEW

**Comment by GasimGasimzada** [comment]
Please refer to the glossary for certain technical words and suffixes to use. Throughout the documentation, we are using React-in not React-ın.

**Comment by GasimGasimzada** [comment]
Please refer to the glossary for certain technical words and suffixes to use. Throughout the documentation, we are using React-in not React-ın.

**Comment by saidfagan** [comment]
Hi. What is the reason of such choice?

**Comment by GasimGasimzada** [comment]
React is pronounced as Reəkt, not Reakt; so, we should suffix it based on pronounciation.

**Comment by saidfagan** [comment]
I've made the requested change. Although, it surpised me that React is pronounced like "Reəkt", I always pronounce it like "Reakt" similar to already existing word in Azerbaijani "reaktiv".

**Pull request merged**
